common: &common
  adapter: postgresql
  username: rails
  password: rails

test:
  <<: *common
  database: cookbook_test

development:
  <<: *common
  database: cookbook_dev

production:
  <<: *common
  database: cookbook_prod
